### ISSUE TITLE
Does it possible to upgrade the preact-cli and save the stable preact 8 version with the custom configuration changes?

### ISSUE THREAD

**Issue by studentIvan** [preactjs/preact-cli#1183]
**Do you want to request a _feature_ or report a _bug_?**
Question/feature
**What is the current behaviour?**
Complex to update.
**If the current behaviour is a bug, please provide the steps to reproduce.**

**What is the expected behaviour?**
Support the previous webpack configuration or show the detailed map how to update it.
**If this is a feature request, what is motivation or use case for changing the behaviour?**

**Please mention other relevant information.**

Please paste the results of `preact info` here.
preact-cli 2.2.1

Does it possible to upgrade the preact-cli and save the stable preact 8 version with the custom configuration changes? Move to Preact X is very dangerous step under the production project, but it could be good to update at least the babel to v7. Can you recommend me something?

Sure it could be good to have an eject possibility. Can't understand why is impossible - we can get the same libraries waht preact-cli using. Can't we?

**Comment by developit** [comment]
There's no eject because preact-cli isn't a configuration, it's a command-line tool. CRA popularized the eject approach, but it's actually a really poor solution that results in folks having to "own" configurations they don't understand.

As for updating, you should be able to run `npm install --save-dev preact-cli@latest` without changing your preact version. The new version of Preact CLI supports both Preact 8 and Preact X.
