### ISSUE TITLE
webpack.ProvidePlugin not working with preact.config.js

### ISSUE THREAD

**Issue by Mathieu-C** [preactjs/preact-cli#1208]
**EDIT: this is a preact issue, I messed up.**

**Do you want to request a _feature_ or report a _bug_?**
bug or wrong configuration on my side

**What is the current behaviour?**
Trying to provide a plugin with `webpack.ProvidePlugin` though the `preact.config.js` I get an error on runtime: `ReferenceError: PIXI is not defined` even though the package is installed correctly.

**If the current behaviour is a bug, please provide the steps to reproduce.**
Here's the configuration:
```js
webpack(config, env, helpers, options) {
  //...
  options = {
    plugins: [
      new webpack.ProvidePlugin({
        PIXI: 'pixi.js',
      }),
    ],
  }
}
```
Install both `pixi.js` and `pixi-layers`dependencies, `pixi-layers` depends on `pixi.js` to be available to work:
```js
import * as PIXI from "pixi.js";
import "pixi-layers";
```
**What is the expected behaviour?**
I expect this config to work the same as an earlier version of my project (before switching to preact):
```js
module.exports = {
  webpack: {
    plugins: [
      new webpack.ProvidePlugin({
        PIXI: 'pixi.js',
      }),
    ],
  },
};
```
This worked fine and provided pixi as expected.

**Comment by RyanChristian4427** [comment]
Are you sure you need the plugin?

Going by `pixi-layers`' instructions, you should just be able able to add the following lines to your index.js/ts, no plugins needed?

```
import * as PIXI from 'pixi.js';
window.PIXI = PIXI;
import 'pixi-layers';
```

Granted this is the first time I'm even hearing of this tool, so perhaps I'm mistaken.

**Comment by Mathieu-C** [comment]
Thanks for your answer, I discussed this with the plugin's author and these instructions are incorrect (I've submitted a PR to fix these).

**Comment by Mathieu-C** [comment]
Sure here's some code from the demo: https://gist.github.com/Mathieu-C/3f98bafc5a7e8fc3364f299407d40d58

You'll need to provide images for the demo to work (line 45 and 46), this works great when I run it in my initial project with `providePlugin` but not with the preact config I've tried.

**Comment by RyanChristian4427** [comment]
It seems a bit touchy, though this could work?

```
const providePlugin = helpers.getPluginsByName(config, 'ProvidePlugin')[0].plugin;
providePlugin.definitions['PIXI'] = 'pixi.js';
```

I say 'touchy' because while I do get an error in the console, I believe that it ends up resolving itself. I'm not sure what the rendering should look like, but what I'm seeing is a V shape with the left half being of one image I provided, the right half being the other.  

I'm not sure if the error can be removed, if it is just a temporary thing and your app otherwise does render correctly. You might need someone more experienced than I to figure that out.

**Comment by Mathieu-C** [comment]
Yes! Even though I do get a lot of warnings thrown at compile, it runs perfectly well. I'm still wondering why I can't simply provide the plugin like in my other webpack config but I guess this will have to do for now.

Thanks a bunch!

**Comment by RyanChristian4427** [comment]
> I'm still wondering why I can't simply provide the plugin like in my other webpack config but I guess this will have to do for now.

I'm not sure what your config file looks like, but [this can help provide context](https://github.com/preactjs-templates/typescript/blob/master/template/preact.config.js) if you're missing parameter descriptions, and [this can help by showing some basic configurations](https://github.com/preactjs/preact-cli/wiki/Config-Recipes).

You can't provide the plugin like you can in a Webpack config because this isn't a Webpack config. In your `preact.config.js`, you write rules that will overwrite the actual Webpack config file that's hidden away. Most people do not like manually dealing with Webpack, as it can be quite the monster, so it is hidden away until when you want to make changes to it.

Had you targeted the right item (`helpers.getPluginsByName(config, 'ProvidePlugin')[0].plugin.definitions`) you would have overwritten the existing configs, likely breaking many things. The CLI needs its own skew of plugins to operate correctly, so that's why we instead just appended to a new value to the `ProvidePlugin`, rather than reassigning it.

**Comment by Mathieu-C** [comment]
Thanks a lot of your insight, I wish preact has a tool like craco I could use to properly override Webpack's config, this will work fine for now!

**Comment by RyanChristian4427** [comment]
> Thanks a lot of your insight, I wish preact has a tool like craco I could use to properly override Webpack's config, this will work fine for now!

Not sure I understand. This is overriding the Webpack config.

In this example, we inserted a new value to the `ProvidePlugin`. If you wanted to, you could just completely override the `ProvidePlugin` with your values, but that would break things, as Preact needs that plugin to operate too. 

The basic configurations link I provided is quite literally overriding the Webpack config in various ways.
