### ISSUE TITLE
pre-rendered data should be HTMLescaped

### ISSUE THREAD

**Issue by prateekbh** [preactjs/preact-cli#1226]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behaviour?**
Any prerendered data is not HTMLEscaped.

**If the current behaviour is a bug, please provide the steps to reproduce.**
Add a `</script> and some test here` to the prerendered data

**What is the expected behaviour?**
- Pre-rendered data should be HTMLEscaped.
- And should be Unescaped before putting into context API

**Comment by developit** [comment]
@prateekbh I've used `devalue` to achieve this in the past. Normally `devalue` produces executable JS, which we don't want because that will block the HTML parser. Passing the data through JSON.stringify() and then through devalue() works around this ([here](https://github.com/preactjs/preact-cli/blob/5dd567867c56510cbb38d7caad86003956d83cc6/packages/cli/lib/resources/body-end.ejs#L2-L4)):

```diff
<script type="__PREACT_CLI_DATA__">
- <%= JSON.stringify(htmlWebpackPlugin.options.CLI_DATA) %>
+ <%= JSON.parse(require('devalue')(JSON.stringify(htmlWebpackPlugin.options.CLI_DATA))) %>
</script>
```
