### ISSUE TITLE
Static HTML renders below VDOM

### ISSUE THREAD

**Issue by peopledrivemecrazy** [preactjs/preact-cli#1259]
**Do you want to request a _feature_ or report a _bug_?** Bug

**What is the current behaviour?** using HTML in template.html renders below VDOM.

**If the current behaviour is a bug, please provide the steps to reproduce.**

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title><% preact.title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <% preact.headEnd %>
  </head>
  <body>
	no html tags
	<p>any html tags</p>

	<% preact.bodyEnd %>
	
  </body>
</html>
```

**What is the expected behaviour?**

any HTML above <% preact.bodyEnd %> should load only above it.

**Please mention other relevant information.**
Global preact-cli version is 2.2.1

**A method to fix the issue**

```html

  <div id="preact_root">
      <% preact.bodyEnd %>
    </div>
```
using the above snippet fixes the issue.

**Comment by reznord** [comment]
That is intended since preact-cli renders the app on document.body. firstElementChild or element with id `preact_root`. You can refer it here: [preact-cli/blob/master/packages/cli/lib/lib/entry.js#L35](https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/entry.js#L35)

If you want to render any static html/scripts inside body before you render your app, you need to do it as you specified in the snippet above 🙃
