### ISSUE TITLE
Error with errors

### ISSUE THREAD

**Issue by access-apps** [preactjs/preact-cli#1346]
I have version three of the command line tool and when an element isn't there, there aren't errors that tell you that it wasn't there. For example, my element was `<React.Fragment>...</React.Fragment>`. And that element was working until deleting `const React = require('react')` from the code, regardless of react not being a module in the modules area. Once deleting that code the screen doesn't render and there isn't an error. The code `<Fragment>...</Fragment>` address the error, there isn't a error though. It isn't only for react either, other elements that aren't there cause the screen not to render. And other errors seem not to be happening either. I don't know if there's a module that shows the errors that were in react.

Thank you for your assistance.

**Comment by RyanChristian4427** [comment]
> I have version three of the command line tool and when an element isn't there, there aren't errors that tell you that it wasn't there. 

Where are you looking for errors? There should be a readout in the console of your browser. For example, if I have the component:

```
function Header() {
    return <NonExistantComponent />
}
```

And I try to use `<Header />`, in the browser console I will see: `Uncaught ReferenceError: NonExistantComponent is not defined`.

Is this error message not showing up for you, or are you looking somewhere else?

> For example, my element was <React.Fragment>...</React.Fragment>. And that element was working until deleting const React = require('react') from the code, regardless of react not being a module in the modules area. 

This is an intentional feature called aliasing. To allow you to use the wider React ecosystem of libraries, the Preact CLI automatically aliases all React references to Preact. So when you or a library were to ask for React, the Preact CLI instead gives Preact in its place. This means you don't have to fork a library just to change `import x from react;` to `import x from preact;`. [Here's the official Preact documentation for aliasing](https://preactjs.com/guide/v10/getting-started#aliasing-react-to-preact).

**Comment by rschristian** [comment]
Closing as it should be answered. Let me know if you have any further questions.
