### ISSUE TITLE
import "async!xxx" shows as error for tsc

### ISSUE THREAD

**Issue by syabro** [preactjs/preact-cli#1473]
**Do you want to request a _feature_ or report a _bug_?**
_bug_

**What is the current behaviour?**
When I want to add async import adding async like `import Home from "async!./pages/home";` generates error 

```
src/app.tsx:4:18 - error TS2307: Cannot find module 'async!./pages/home' or its corresponding type declarations.

4 import Home from "async!./pages/home";
```

**If the current behaviour is a bug, please provide the steps to reproduce.**

1. Add `async` somewhere in code 
2. Run `tsc -p .`

**What is the expected behaviour?**
Tsc doesn't generate the error

Please paste the results of `preact info` here.

```
Environment Info:
  System:
    OS: macOS 11.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 15.2.1 - /var/folders/4y/qq10l7dn0jg84ww2hzylc2mc0000gn/T/yarn--1605945844645-0.6938824385815894/node
    Yarn: 1.22.10 - /var/folders/4y/qq10l7dn0jg84ww2hzylc2mc0000gn/T/yarn--1605945844645-0.6938824385815894/yarn
    npm: 7.0.10 - /usr/local/bin/npm
  Browsers:
    Firefox: 83.0
    Safari: 14.0.1
  npmPackages:
    preact: ^10.5.7 => 10.5.7
    preact-cli: ^3.0.0 => 3.0.3
    preact-render-to-string: ^5.1.4 => 5.1.12
    preact-router: ^3.2.1 => 3.2.1
```

**Comment by rschristian** [comment]
Use `preact build` to build your Preact CLI project. The async import comes from `@preact/async-loader` which the CLI uses but TSC is entirely unaware of.

**Comment by syabro** [comment]
@rschristian WebStorm uses `tsc` to  track and show errors. Does it mean I have to choose between `async!` and WebStorm?

**Comment by rschristian** [comment]
You might be able to setup some sort of shenanigans with your `tsconfig` paths and your `preact.config.js`, but that may be difficult.

Is there any particular reason you're not placing your files in [the directories that automatically get the async treatment](https://github.com/preactjs/preact-cli#route-based-code-splitting)? Probably the simplest solution. Instead of (presumably) `src/pages/home`, use `src/routes/home` or `src/async/home`. It does require renaming directories but that requires no special environment changes. Just normal imports.

If you're really married to `pages/`, you may be able to [override the config from `routes` to `pages` here](https://github.com/preactjs/preact-cli/blob/67fafc8e3d0d98665a193e10bc7c9a1ce2aeeedf/packages/cli/lib/lib/webpack/webpack-client-config.js#L56-L83) but I'm not sure that I'd recommend that. There's a few other hard-coded uses of `routes` like with the CSS loader, so this (might) require a few config overrides.

**Comment by syabro** [comment]
@rschristian thank you!

I've googled what can I do about, and looks like it's impossible with `TS`. But I can go with dynamic imports.
