### ISSUE TITLE
Shadow dom widget

### ISSUE THREAD

**Issue by RWOverdijk** [preactjs/preact-cli#1547]
**What is the current behaviour?**

I'm creating a widget of sorts and looked at the widget template. It seems outdated and doesn't work the way I want it to.

The default/typescript templates create more than I need. For example, I don't need an index.html file because the widget only uses js. This seems to be an issue with the css, which gets added to the head of the html.

**What is the motivation or use case for changing this behaviour?**

I'm creating a widget that places itself onto a page. It's a simple approach that looks more or less like this:

```jsx
import { h, render } from 'preact';
import { Widget } from './Component/Widget';

const style = document.createElement('style');

style.textContent = `
  /* css goes here. */
`;

const shadowTarget = document.createElement('div');
shadowTarget.id = 'my-widget';

document.body.appendChild(shadowTarget);

const shadow = shadowTarget.attachShadow({ mode: 'open' });
const shadowRoot = document.createElement('div');

shadowRoot.id = 'shadow-root';

shadow.appendChild(style);
shadow.appendChild(shadowRoot);

render(<Widget />, shadowRoot);
```

This is what I'd like to accomplish. A css and js-only widget where the css gets added to the shadow dom instead of the html, which I don't have. The default template comes with really nice default stuff set up which I'd prefer to not have to set up myself _(webpack hates me. And the feeling is mutual)_.

**Describe the solution you'd like**

1. I'd prefer to be able to tell where to put the css (in the shadow root).
2. I'd like a way to not build an index.html, as in the end all I need is a js file.

I feel like this could be accomplished already, since the css is being created. All it would take is adding that css to a js file somewhere. As to not creating the html file, all it would take is not processing the index.html file. The only thing that would need a change is the polyfill.

If this is something I can already do myself I'm sorry for creating this issue. If you could help me on my way that'd be very kind.

**Please mention any other relevant information.**

N/A

**Comment by rschristian** [comment]
(FWIW, I do have forks of each that _should_ be up-to-date, and would recommend using them as the basis)

The HTML file is only used for testing. In dev, both run Preact-CLI and use that HTML file as the template to attach the widget to. Get rid of that HTML and how can you actually test anything? That's the only reason it's there, it's not included in the bundle.

The TS-Widget is a bit wonky, as it uses Preact CLI to build for some reason (no idea what the original thought was there) but should still generate a JS bundle that is what you'd actually use. 

> I feel like this could be accomplished already, since the css is being created. All it would take is adding that css to a js file somewhere.

So this is actually super easy (and is something I lobbied for). Microbundle has a `--css inline` flag so that the following can be done:

```
// with `microbundle --css inline`:
import css from './foo.css';
console.log(css);  // the generated minified stylesheet
```

With this, you can write your styles in a normal style sheet, no need for template strings, and then the files will be inlined as a minified string right into your JS, which sounds like exactly what you want.

**Comment by rschristian** [comment]
Took me a bit longer than expected to get a decent dev experience, but here's the repo: https://github.com/rschristian/example-widget-for-1547

I've pushed a build as well so you can inspect it. Let me know if this works for you.

**Comment by RWOverdijk** [comment]
@rschristian thank you for the detailed reply, you're too kind. After your efforts I feel bad saying that it seems like it might not be what I meant.

I noticed that the approach here is to [inline the css in at least one component](https://github.com/rschristian/example-widget-for-1547/blob/master/src/component.js#L8). I think the idea is to have the css and the components not have a relationship with each other and just inline all the css in app? That's not exactly what I had in mind. What I want to accomplish is an auto-prefixed css that gets added in the shadow dom (could be app, that part isn't super important to me). I still want to use scss and classnames instead of plain css. So instead of importing styles from within the main stylesheet, I want to import them inside of my components.

With parcel for example I currently do this:

```jsx
import { h } from 'preact';
import styles from './styles.scss';

export function Example() {
  return <div class={styles.exampleClass} />
}
```

It then transpiles the css and replaces the class with the name of the created class. The css ends up in a css bundle and gets added in the head of the html file. So inside of my preact components it should use class names, and the result should all be added in the shadow dom instead of the main html file.

Maybe what I want is too far off from what the templates are doing and I shouldn't be asking this question here. Or maybe I just don't understand (it happens more often lol).

One of the reasons I wanted this approach is because preact-habitat seems unmaintained.

**Comment by rschristian** [comment]
Oh, so what you want are CSS Modules? That's what it's called when you do `<div class={style.class} />`. 

CSS Modules and Shadow DOM are mutually exclusive I believe. You'd need to import the sheet as a string, while also importing the sheet as an object. Object to assign class names to your elements, sheet in order to actually assign it into the style tag. You can't do that in any sort of reasonable fashion. Your issues just comes down to the fact that you can't really do both CSS modules and Shadow Dom. They're competing ways of scoping styles. Like scoped within scoped. Wouldn't make sense, even if you could do it.

`preact-habitat` hasn't been touched in a bit but really doesn't need to be. It works just fine currently. I didn't even intend to swap it out, only noticed that now. The templates are designed for standard Preact components, either as something you can inject into HTML, or as a component library. Certainly easy to manipulate them into this though, I only had to change up the the entry point to get (sort of) what you wanted.

**Comment by RWOverdijk** [comment]
I see, thank you.

I didn't it was called css modules, I'll look into that. It would be cool if I could get it to work. This "css modules" thing still puts the styles in the head of my html, so it's doing what I want it to do, but it's doing it in the wrong place. If I can redirect that to be a string in my js file I'll have exactly what I want. 😄 I'll try to get that going as it's way too offtopic for this issue.

By the way, I tried using your typescript widget fork and noticed that it creates a separate css file when running `build:widget`. It doesn't attempt to load it or embed it (or so it seems), so I have to separately serve and include that file to see my styles applied at all. I know this is also offtopic, but I thought I should mention it.

And once more: thank you for your help! I appreciate it.

**Comment by rschristian** [comment]
> I didn't know it was called css modules, I'll look into that. It would be cool if I could get it to work. This "css modules" thing still puts the styles in the head of my html, so it's doing what I want it to do, but it's doing it in the wrong place. If I can redirect that to be a string in my js file I'll have exactly what I want. 

Yeah you can't do that is the issue. CSS Modules have you import the style sheet as if it were an object, where the classes are the keys (`stylesheet.className`, etc). In order to inject it anywhere but the head, you'd need to import that as a string, and manually inject (as you were sort of doing in the first comment). So you'd need to simultaneously load the file in two very different formats, which obviously is a no-go. 

Both do the same thing, scope CSS, but they are competing standards. Can't work in unison.

> By the way, I tried using your typescript widget fork and noticed that it creates a separate css file when running build:widget. It doesn't attempt to load it or embed it (or so it seems), so I have to separately serve and include that file to see my styles applied at all.

Yes, that's correct. You cannot actually import CSS into JS. We do it in web apps where things like Webpack or Rollup handle that, but that's totally against the spec and absolutely incorrect. So when bundling for production, you can either inline the CSS into the JS or have them as separate files that need to be separately imported. It's the only spec-compliant way. Here's a great thread on this if you're curious to learn more: https://github.com/developit/microbundle/issues/416

There's some recent talks with TC39, the JS spec committee, about adding CSS (and other) file type imports, but currently there is nothing official. 

Certainly let me know if you have anymore questions or I can help with something else. Sorry we couldn't get exactly what you were hoping for here, but maybe this is close.

**Comment by RWOverdijk** [comment]
> Yeah you can't do that is the issue.

That's so weird, because I can. I don't know how/why, but using a fresh setup with parcel I can import styles and assign them to `class`. It transpiles if the file is less/scss and puts it in a separate file, replacing my import and assignment with just the class name. So it already makes a regular stylesheet _and_ allows me to assign it in js. Maybe it doesn't use css modules but uses something else? I know parcel has a bunch of transforms running in a certain order. I'll investigate why this thing that shouldn't work, seems to work. I like mysteries lol.

> Yes, that's correct. You cannot actually import CSS into JS. 

Ah, now I understand! But I didn't mean import. I meant embed/load into the shadow dom (which is the only way to do it: since there's no actual html file, you have to load it through js). It's like the code I posted in the issue, where the inline css could also be a URL pointing to a cdn (although I prefer embedding it). .

```jsx
import { h, render } from 'preact';
import { Widget } from './Component/Widget';

const style = document.createElement('style');

style.textContent = `
  /* css goes here. */
`;

const shadowTarget = document.createElement('div');
shadowTarget.id = 'my-widget';

document.body.appendChild(shadowTarget);

const shadow = shadowTarget.attachShadow({ mode: 'open' });
const shadowRoot = document.createElement('div');

shadowRoot.id = 'shadow-root';

shadow.appendChild(style);
shadow.appendChild(shadowRoot);

render(<Widget />, shadowRoot);
```

If I make any progress in achieving what I want I'll drop it here. I started this journey yesterday so there's a lot of magic happening in my project still. Templates are cool, but you have to reverse engineer everything to understand what the hell is going on. I'll be back 😛

**Comment by rschristian** [comment]
> That's so weird, because I can. I don't know how/why, but using a fresh setup with parcel I can import styles and assign them to class. It transpiles if the file is less/scss and puts it in a separate file, replacing my import and assignment with just the class name. So it already makes a regular stylesheet and allows me to assign it in js.

That's just standard CSS Modules and we do that by default for a few directories. That's no problem. The problem is you want to import your stylesheet as an object (CSS Modules) and as a string (shadow dom). One or the other. Can't have both versions.

>  It's like the code I posted in the issue, where the inline css could also be a URL pointing to a cdn (although I prefer embedding it). .

So this is the pain point. If you're using CSS Modules, your CSS file is treated like an object. How can you embed the object and still have it treated like CSS? You can't. 

It's super easy to do either or, but combined, no. Feel free to Google "CSS Modules and Shadow Dom", every result you're gonna find is saying one is better than the other really. You can't use both. 

Sorry if I'm not explaining this well, kinda complex topics that have a lot going on when it comes to bundler/loaders/and various web standards.
