### ISSUE TITLE
Generate one JavaScript file on build

### ISSUE THREAD

**Issue by byshine** [preactjs/preact-cli#1606]
**What is the current behaviour?**
Can't find any easy presets to allow this to happen

**What is the motivation or use case for changing this behaviour?**
Need to embed a build to another app

**Describe the solution you'd like**
Allow to generate 1 big minified js bundle.

I need to be able to generate 1 big bundle, no chunks, all js in 1 file. Is there an easy way to do this?

**Comment by rschristian** [comment]
`routes/` are automatically code split, so if you rename that directory to anything else it will remove the chunks. it won't create a single `bundle.js`, but it's closer.

That being said, Preact-CLI is a tool for creating PWAs, so this really isn't the target for it and it likely isn't an ideal solution because of that. Are you sure you want to build an app and embed it somewhere? Or are you simply looking to bundle some components?

**Comment by rschristian** [comment]
This is more of a task for something like [Microbundle](https://github.com/developit/microbundle)
