### ISSUE TITLE
Duplicated critical css

### ISSUE THREAD

**Issue by caxapexac** [preactjs/preact-cli#1631]
**What is the current behaviour?**
Inlined critical styles:
![image](https://user-images.githubusercontent.com/33996246/146496759-b367bb2f-7307-4522-b15d-5d26a7091661.png)
Also exists in this bundle:
![image](https://user-images.githubusercontent.com/33996246/146496819-ca7194d6-dd05-4b30-910d-dca5f7e1037e.png)
![image](https://user-images.githubusercontent.com/33996246/146496876-c776964a-7d55-41fd-b1c4-05ca72b38156.png)
Which is includes into build
How to control

**Steps to Reproduce**
Just `preact build`

**What is the expected behaviour?**
Part of css is critical so I can choose what to inline and what to place into bundle.css

Btw how to control which css files are inlined at all? No info in readme

**Comment by rschristian** [comment]
This is intentional and correct. `bundle.css` needs to have the full styles, but inlining critical styles ensures fast first paint. The benefits of this should outweigh the cost of a few duplicated styles.

[Critters](https://github.com/GoogleChromeLabs/critters) is used to generate critical CSS.

> Btw how to control which css files are inlined at all? No info in readme

CSS files aren't inlined, critical styles are. I don't know what you're looking to control. Input stylesheets? You can't, AFAIK. You could reduce the built stylesheets that Critters can use to generate critical styles, but I don't know why you would. Below is how you could alter it.

preact.config.js
```js
export default (config, env, helpers) => {
  const critters = helpers.getPluginsByName(config, 'Critters')[0];
  if (critters) {
    critters.plugin.option.additionalStylesheets = [ '*.css' ];
  }
}
```

**Comment by caxapexac** [comment]
Oh I just understood critters finds critical css automatically, so duplicating makes sense
