### ISSUE TITLE
2 index.html files created upon build

### ISSUE THREAD

**Issue by TbirdDuncan** [preactjs/preact-cli#1656]
Same as title, running npm run build produces 2 index.html files that are identical, one is named 200.html and the other index.html

**Comment by rschristian** [comment]
You can read about it here: https://github.com/preactjs/preact-cli/pull/1441

**Comment by TbirdDuncan** [comment]
I'm very curious I posted a question in discussions here about the file size of the build. I'm also curious running a profiler on both apps one with preact and the other with react, shows me that react is takes less time to load...

**Comment by rschristian** [comment]
Will answer that then, and I think I'll make a wiki to explain our outputs and why they exist.

Need a lot more info in order to diagnose build size and perf issues. Do note, that Preact v React + DOM is about 35kb (I believe) these days. That's pretty big if you're comparing UI libraries and using them raw on the page, however, in an app, this can easily be overshadowed by other issues. If your main bundle ends up being 600kb (for example) that 35kb will be rather irrelevant.
