### ISSUE TITLE
The Wiki is insecure

### ISSUE THREAD

**Issue by modster** [preactjs/preact-cli#1687]
**What is the current behaviour?**
I was perusing the preact-cli wiki, and noticed I was able to edit pages, make new pages, edit menus, anything! I didn't touch anything, but maybe the next stranger isn't so nice. Someone should look into that. 
![Screenshot 2022-04-17 135825](https://user-images.githubusercontent.com/893946/163730414-c3ddeb2e-e26d-4942-aa51-c0e084d3f9a6.png)

**Comment by rschristian** [comment]
I believe this is intentional, as it allows users to add docs/configs that they may find useful (rather than pinging one of us to do it for them).

[There is a full revision history for each page](https://github.com/preactjs/preact-cli/wiki/Config-Recipes/_history), so if anyone were to graffiti (has not happened yet), it's easy to rollback and ban the user. Not a problem at this point in time.
