### ISSUE TITLE
Typescript linter errors when importing semantic-ui-react library into preact-cli typescript template.

### ISSUE THREAD

**Issue by judilsteve** [preactjs/preact-cli#1692]
**What is the current behaviour?**

The preact-cli typescript template shows eslint errors in the build log and in my IDE (VS Code) for some components in [semantic-ui-react](https://www.npmjs.com/package/semantic-ui-react)

![image](https://user-images.githubusercontent.com/4328790/167824477-f72c9a72-21b9-4bfa-a6d9-6c84f52ca8b3.png)

These do not seem to prevent the build from completing and the resulting application appears to work fine, but in the project that I am trying to migrate from react to preact this is creating a lot of linter noise which is preventing me from seeing actual issues in my code.

**Steps to Reproduce**

See [sample repo](https://github.com/judilsteve/preact-cli-ts-test) with minimal reproducing code. Steps to create sample repo below:

1. Create an empty preact-cli project from the typescript template: `npx preact-cli create typescript preact-cli-ts-test`
2. Install semantic-ui-react: `cd preact-cli-ts-test && npm i --save semantic-ui-react`
3. Add the line `import { Header } from 'semantic-ui-react';` near the top of `src/routes/home/index.tsx`
4. Add the line `<Header>This is a header</Header>` inside the return statement of the Home component in the same file

**What is the expected behaviour?**

There should not be any linter errors related to the new code in the build log or in the user's chosen IDE

**Please mention any other relevant information**

N/A (please let me know if you need anything else)

**Output of `npx preact-cli info`:**

```
Environment Info:
  System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 101.0.4951.54
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.39)
  npmPackages:
    preact: ^10.3.1 => 10.7.2
    preact-cli: ^3.0.0 => 3.3.5
    preact-render-to-string: ^5.1.4 => 5.2.0
    preact-router: ^3.2.1 => 3.2.1
```

**Comment by rschristian** [comment]
> These do not seem to prevent the build from completing and the resulting application appears to work fine,

We don't stop the dev build from completing due to TS errors, but this will actually block production builds, so that's something to be aware of.

It looks like their types are outdated and broken with the release of React v18. Can you try downgrading `@types/react` by manually installing `@types/react@^17`? That corrects it for me.

We enable `skipLibCheck` in the default `tsconfig.json` to stop errors from libraries stopping your builds, but this means the issues can become a bit hidden when they do exist.

You might want to bring this issue upstream to get a better fix, nothing we can really do in that regard as it's their types.

Make sure to also check out https://github.com/preactjs-templates/typescript/issues/71, as that'll stop builds too at the moment. Might have to just disable type-checking the tests ourselves, as Enzyme doesn't seem to want to fix their incorrect type declaration.

**Comment by judilsteve** [comment]
![image](https://user-images.githubusercontent.com/4328790/168027507-f35a7f87-ada4-44a5-8597-1ee0f1c3b577.png)

`npm i --dev @types/react@^17` fixed my issue!

Thanks for providing the solution, I was playing with tsconfig flags all night to no avail. Hopefully this github issue can help others who encounter the same problem trying to use pre-react-18 vanilla-react component libraries with preact.

Thanks!

**Comment by judilsteve** [comment]
FYI for anyone else trying to use semantic-ui-react with preact + ts:

There is an [open issue](https://github.com/Semantic-Org/Semantic-UI-React/issues/4354) concerning React 18 support.

**Comment by rschristian** [comment]
Glad to hear it! Bit of a blind guess, but seemed to work out.

I'll close this out now, as it seems to be an upstream issue anyhow, but certainly feel free to reply if you run into any other issues.
