### ISSUE TITLE
Can't resolve 'preact-cli-entrypoint'

### ISSUE THREAD

**Issue by xuya227939** [preactjs/preact-cli#1789]
**What is the current behaviour?**
npx preact-cli create default my-project error

**Steps to Reproduce**

1. preact-cli create
```
npx preact-cli create default my-project
```

2. npm run dev

error 

```
> cross-env NODE_OPTIONS=--openssl-legacy-provider preact watch

node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

3. Update openssl-legacy-provider by package.json

```
cross-env NODE_OPTIONS=--openssl-legacy-provider preact watch
```

npm run dev

```
Can't resolve 'preact-cli-entrypoint'
```

node -v

```
v16.18.0
```

preact -v

```
preact, 3.4.5
```

**Comment by rschristian** [comment]
In the future, follow the bug report template rather than deleting it. I need you to provide the output of `npx preact info`, as that template instructed.

I cannot reproduce either issue.

> cross-env NODE_OPTIONS=--openssl-legacy-provider preact watch
>
> node: --openssl-legacy-provider is not allowed in NODE_OPTIONS

If you're on Node 16, as you seem to indicate, not only is `--openssl-legacy-provider` supported, but it's necessary. You won't be able to run Webpack without it. Are you somehow using Node 14 in your app? Check to make sure you don't somehow have multiple Node versions installed.

> Can't resolve 'preact-cli-entrypoint'

Did you move files around after creating the project? `preact-cli-entrypoint` resolves to any `index` file within `src/`:

https://github.com/preactjs/preact-cli/blob/8d65d945059c569f81288c445ec9868b2a71a5df/packages/cli/src/lib/webpack/webpack-base-config.js#L143

I'm not sure how you'd get this error unless you're leaving out information.

**Comment by xuya227939** [comment]
I solved it, Thank you.

**Comment by rschristian** [comment]
Anything we need to fix on our side?

**Comment by xuya227939** [comment]
Nothing, Thank you. @rschristian
