### ISSUE TITLE
webpackJsonp is not defined while using CommonsChunkPlugin

### ISSUE THREAD

**Issue by amitverma** [preactjs/preact-cli#707]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behaviour?**
Getting webpackJsonp as undefined while trying to use CommonsChunkPlugin in Preact-CLI, trying to generate a separate vendor.js

**If the current behaviour is a bug, please provide the steps to reproduce.**

```javascript
config.plugins.push(
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      filename: 'vendor.[hash].js',
      minChunks: ({ resource }) => (
        resource !== undefined &&
        resource.indexOf('node_modules') !== -1
      ),
    })
  )

  config.plugins.push(
    new webpack.optimize.CommonsChunkPlugin({
      name: 'main',
      children: true,
      async: true,
      minChunks: ({ resource }) => (
        resource !== undefined &&
        resource.indexOf('node_modules') !== -1
      ),
    })
  )

While trying to use this in `preact.config.js`, I get the following error when I try to load the app:
`bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined`

**What is the expected behaviour?**
It should generate vendor.js and main.js and the app should load without any error

**Comment by prateekbh** [comment]
So with this approach due to all node_modules in `vendor.js` the `webpackJsonP` function goes into vendor bundle.

but due to this: https://github.com/developit/preact-cli/blob/master/src/resources/template.html#L28

bendle gets included before vendor and thus the error. you should make sure in this case that `vendor` is included before anything else in the markup.

**IMP:** This approach can backfire at you, imagine a node module being used remotely at some page, but now that is in `vendor` bundle. And will be required to load for your every single page(whether they require use it or not).

**Comment by MrCoder** [comment]
@prateekbh Then what is the recommended way to fix this issue?

**Comment by prateekbh** [comment]
If you decide to go this path, make a custom template where `vendor.js` is loaded before anything else
