### ISSUE TITLE
Bootstrap min-width rule on body, only on builds

### ISSUE THREAD

**Issue by qualitymanifest** [preactjs/preact-cli#943]
When building my app with `preact build`, `body` ends up with `min-width: 992 !important;` on it. When I look at the CSS bundle file in devtools it looks like this is coming from Bootstrap, but I have no idea why. It's only a problem on builds - when running the dev server it's fine.

here is my `app.js`:
```js
import "bootstrap/dist/css/bootstrap.min.css";
import "./style";
import App from "./components/app";

export default App;
```

### versions 
preact@10.2.1, same issue with 10.0.1
preact-cli@3.0.0-rc6
bootstrap@4.4.1, also tried 4.3.1

**Comment by marvinhagemeister** [comment]
This issue is very likely not related to `preact` or `preact-cli`. I just verified with our source code and the ones in our template organization that neither of those has this `min-width: 992 !important;` CSS rule anywhere. You're best shot is asking the bootstrap team about it.

If you do manage to provide more information and in the ideal case provide a simple codesandbox/github repo with a dummy app, you can make sure that the other person is seeing what you are seeing on your screen.

A wild guess: It could be that bootstrap does something different depending on if it's running in prod or not. It may be caused by some sort webpack loader or some of their components. It could even be a browser extension that messes with the pages CSS. Another possibility could be a stale service worker that's running in the background that is from another project if you're working on localhost.

It's really hard to tell based on the amount of information provided, so I can only make guesses. In either way it's very likely not related to anything surrounding `preact` or `preact-cli`.
